Repository DSC-University-of-Seoul/raccoon-frontend, pull requests merged in 2021-02, with the labels that each got.

#2 revised) #1 Prettier Lint 준수
  .eslintcache
  src/App.test.js
  src/components/page/CreateRoom.js
  src/components/page/EnterRoom.js
  src/components/page/index.js
  src/index.js
  src/reportWebVitals.js
Labels: lint

#13 Style#12
  src/fonts/NanumGothic-Regular.ttf
  src/fonts/RobotoMono-Bold.ttf
  src/fonts/VT323-Regular.ttf
  src/index.css
  src/index.js
Labels: enhancement, help wanted

#16 Header#15
  package-lock.json
  src/App.js
  src/components/UI/Header.js
  src/components/UI/index.js
  src/components/page/CreateRoom.js
  src/scss/components/_header.scss
  src/scss/main.scss
Labels: enhancement, help wanted

#18 Style#14
  src/App.js
  src/components/page/ColorPalette.js
  src/components/page/index.js
  src/index.js
  src/theme.js
Labels: enhancement

#21 color palette를 scss variables로 등록 #14
  src/scss/base/_variables.scss
Labels: enhancement

#20 Raccoon list page 구현#7
  package-lock.json
  package.json
  src/App.js
  src/components/UI/RaccoonListUi.js
  src/components/UI/index.js
  src/components/page/RaccoonList.js
  src/components/page/index.js
  src/scss/components/_header.scss
  src/scss/components/_rclist.scss
  src/scss/main.scss
Labels: enhancement, help wanted

#22 Enter room#3
  README.md
  src/App.js
  src/components/page/EnterRoom.js
  src/components/page/Main.js
  src/components/page/Play/Nickname.js
  src/components/page/Play/Pin.js
  src/components/page/Play/index.js
  src/components/page/index.js
  src/scss/components/_header.scss
  src/scss/components/_main.scss
  src/scss/components/_nickname.scss
  src/scss/components/_pin.scss
  src/scss/main.scss
Labels: enhancement
